lein: lein2
language: clojure
install: lein2 deps
script: lein2 javac && lein2 test
notifications:
  recipients:
    - oleksandr.petrov@gmail.com
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
branches:
  only:
    - master
